// flow-typed signature: dd76ec8df8f6d63a1069d3c1141560bb
// flow-typed version: <<STUB>>/string-length_v^1.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-length'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-length' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'string-length/index' {
  declare module.exports: $Exports<'string-length'>;
}
declare module 'string-length/index.js' {
  declare module.exports: $Exports<'string-length'>;
}
